### login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin123"
}

### Insere um usuário
POST http://localhost:8080/usuarios
Content-Type: application/json

{
    "nomeCompleto": "Cristiano Ronaldo",
    "email": "cr7@gmail.com",
    "telefone": "123",
    "senha": "123",
    "cpf": "11111111111",
    "dataNascimento": "1985-02-05",
    "biografia": "Robozão",
    "fotoPerfilURL": "01",
    "endereco": "Espanha",
    "instituicao": "Real Madrid",
    "organizacao": "Portugal"
}

### Insere um usuário
POST http://localhost:8080/usuarios
Content-Type: application/json

{
    "nomeCompleto": "Messi",
    "email": "messi@gmail.com",
    "telefone": "124",
    "senha": "123",
    "cpf": "11111111112",
    "dataNascimento": "1987-06-24",
    "biografia": "E.T.",
    "fotoPerfilURL": "02",
    "endereco": "Espanha",
    "instituicao": "Barcelona",
    "organizacao": "Argentina"
}

### Insere um usuário
POST http://localhost:8080/usuarios
Content-Type: application/json

{
    "nomeCompleto": "Neymar",
    "email": "neymar@gmail.com",
    "telefone": "125",
    "senha": "123",
    "cpf": "11111111113",
    "dataNascimento": "1992-02-05",
    "biografia": "Príncipe",
    "fotoPerfilURL": "03",
    "endereco": "Brasil",
    "instituicao": "Santos",
    "organizacao": "Brasil"
}

### Insere um usuário
POST http://localhost:8080/usuarios
Content-Type: application/json

{
    "nomeCompleto": "Ronaldo",
    "email": "r9@gmail.com",
    "telefone": "126",
    "senha": "123",
    "cpf": "11111111114",
    "dataNascimento": "1976-09-18",
    "biografia": "Fenômeno",
    "fotoPerfilURL": "04",
    "endereco": "Brasil",
    "instituicao": "Aposentado",
    "organizacao": "Brasil"
}

### Insere um usuário
POST http://localhost:8080/usuarios
Content-Type: application/json

{
    "nomeCompleto": "Ronaldinho",
    "email": "r10@gmail.com",
    "telefone": "126",
    "senha": "123",
    "cpf": "11111111115",
    "dataNascimento": "1980-03-21",
    "biografia": "Bruxo",
    "fotoPerfilURL": "05",
    "endereco": "Brasil",
    "instituicao": "Aposentado",
    "organizacao": "Brasil"
}

### Lista todos os usuários
GET http://localhost:8080/usuarios

### Busca usuário por ID
GET http://localhost:8080/usuarios/

### Deleta usuário
DELETE http://localhost:8080/usuarios/